##############################
# --- USER CONFIGURATION --- #
##############################

title: '0xA79D2E'
description:
url: https://shygaan.info
repository: shygaan/shygaan.info

##############################################
# --- ANALYTICS CONFIGURATION (OPTIONAL) --- #
##############################################

jekyll_analytics:        # Uncomment desired analytics tracker and input details
#  GoogleAnalytics:          # Uncomment section if you want to track with Google Analytics
#    id: UA-123-456          # Required - replace with your tracking id
#    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

#  Matomo:                   # Uncomment section if you want to track with Matomo (former Piwik Analytics)
#    url: matomo.example.com # Required - url to Matomo installation without trailing /
#    siteId: "1234"          # Required - replace with your Matomo site id (Write id as string)

#  Piwik:                    # Uncomment section if you want to track with Piwik
#    url: piwik.example.com  # Required - url to Piwik installation without trailing /
#    siteId: "1234"          # Required - replace with your Piwik site id (Write id as string)

#  MPulse:                   # Uncomment section if you want to track performance with mPulse
#    apikey: XXXXX-YYYYY-ZZZZZ-AAAAA-23456   # Required - replace with your mPulse API key

#  Plausible:
#    domain: 'example.com'   # The domain configured in plausible
#    source: 'https://plausible.example.com/js/plausible.js' # The source of the javascript

#################################
# --- EXOCORE CONFIGURATION --- #
#################################
exclude:
  - "404.html"

baseurl: ''
source: .
destination: _site
background: "red"
highlighter: rouge
gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  footnote_backlink: "↲"

last-modified-at:
  date-format: '%B %d, %Y' # Change the format of the 'last modified' date.

readme_index:
  enabled: true

sass:
    sass_dir: ./exocore/_sass

layouts_dir: ./exocore/_layouts
includes_dir: ./exocore/_includes
plugins_dir: ./exocore/_plugins
data_dir: ./exocore/data

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      date: "Jan 1 2000"
  - scope:
      path: ""
    values:
      image:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "journals"
    values:
      layout: "journal"
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki"
  - scope:
      path: ""
      type: "daily"
    values:
      layout: "daily"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "academics"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "note"


collections:

  music:
    output: true
    permalink: /:collection/:slug
  academics:
    output: true
    permalink: /:collection/:slug
  wiki:
    output: true
    permalink: /:collection/:slug

  journals:
    output: true
    permalink: /:collection/:slug

  articles:
    output: true
    permalink: /:collection/:slug

  daily:
    output: false
    permalink: /:collection/:slug

  notes:
    output: true
    permalink: /:collection/:slug

relative_links:
  enabled:     true
  collections: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

graphviz:
  options: "-Tsvg" # 'dot' command option
  command: "dot"   # execute this string. specify full path to 'dot' if you need

# Configure your network graph:

graph:
  enabled: true
  exclude: []
  path:
    assets: "/assets"
    scripts: "/js"
  net_web:
    enabled: true
    exclude:
      attrs: false
      links: false
    force:
      charge: -400
      strength_x: 0.2
      x_val: 0.1
      strength_y: 0.2
      y_val: 0.1
  tree:
    enabled: false
    force:
      charge:
      strength_x:
      x_val:
      strength_y:
      y_val:

include:
  - .well-known/discord

plugins:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
# - jekyll-github-metadata
- jekyll-seo-tag
- html-proofer
- rubocop
- w3c_validators
# - jekyll-last-modified-at
- jekyll-redirect-from
- jekyll-feed
- jekyll-wikilinks
- jekyll-graph
- jekyll-feed